config/routes.rb
Omrails::Application.routes.draw do
get 'about' => 'pages#about'

root :to => 'pages#home'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end


	def action
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
			<small>
				<a <a href="http://aboutme/joshuaefron"> One Month Rails</a> by Joshua Efron
			</small>	

		</div>	

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
 
      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
 
      <!-- Be sure to leave the brand out there if you want it shown -->
      <a class="brand" href="#">One Month Rails</a>
 
      <!-- Everything you want hidden at 940px or less, place within here -->
      <div class="nav-collapse collapse">
      	<ul class="nav">
	        <li><%= link_to "Home", root_path %><li>
			<li><%= link_to "About", about_path %><li>
		</ul>	
		<ul class="nav pull-right">
	        <li><%= link_to "Login", '#' %><li>
		</ul>	
      </div>
 
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>One Month Rails</title>
	  <%= stylesheet_link_tag    "application", :media => "all" %>
	  <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
		<%= render 'layouts/header' %>
		<div class="container">
		<%= yield %>
		<%= render 'layouts/footer' %>
		</div>
	</body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>
<p>
	<%= link_to "One Month Rails", "http://onemonthrails.com" %>
	is a project to teach
	<%=link_to "Ruby on Rails", "http://rubyonrails.org" %>
	in one month. This is the sample application.
</p>	

app/views/pages/home.html.erb
<div class="hero-unit">
	<h1>Welcome to One Month Rails!</h1>
	<p>
		You've found the home page for the
		<%=link_to "One Month Rails", "http://onemonthrails.com" %> application.
	</p>
	<p>
		<%= link_to "Sign Up Now!", "#", class: "btn btn-primary btn-large" %>
	</p>
</div?